### ISSUE TITLE
文件夹目录选择器的扩展建议

### ISSUE THREAD

**Issue by stars-one** [kongzue/DialogXSample#11]
1. 现在每次进入打开的目录都是内置SD卡的目录,主要是考虑到用户之前设置过目录,之后会再次更改的情况,需要可以**支持默认设置打开指定目录**
2. 希望可以文件夹选择器的UI页面中**提供一个新建文件夹的按钮功能**

功能十分好用 感谢!! 👍

**Comment by kongzue** [comment]
请更新至 0.0.7 版本：
- 升级 DialogX 版本至 0.0.46.beta1；
- FileDialog 支持使用 setPath(string/File) 设置默认路径；
请注意新版本使用了最新版本的 DialogX，如果有使用到自定义主题相关接口会发生一定的变更。

**Comment by kongzue** [comment]
DialogXSample 本质上只是个 Demo，提供了一种比较简单的示例写法，也没有做很完善的 API 接口支持，我个人更建议下载源代码，将 [FileDialog](https://github.com/kongzue/DialogXSample/tree/master/FileDialog) 的 Module 单独引入到自己的项目里，其代码非常易于修改，根据具体需要进行功能的调整和变更。

**Comment by stars-one** [comment]
收到
